{% set name = "napari-omaas" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-omaas-{{ version }}.tar.gz
  sha256: 92432eb8e2364f3379e09706e3217b2ffa3cb8b80b62bbf5a4291a6eb8dbb127

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - sif-parser

test:
  imports:
    - napari_omaas
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rjlopez2/napari-omaas
  summary: napari-OMAAS stands for Optical Mapping Acquisition and Analysis Software
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - rjlopez2
